# Generated by Django 4.1.4 on 2023-01-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_restaurant_id_foodtype_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=50)),
                ('postal', models.SlugField(default='00-000', max_length=6)),
                ('street', models.CharField(default=None, max_length=100)),
                ('building', models.PositiveIntegerField(default=None)),
            ],
        ),
    ]
