# Generated by Django 4.1.4 on 2023-01-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_restaurantadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantadress',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.restaurant'),
            preserve_default=False,
        ),
    ]
