# Generated by Django 4.1.4 on 2023-01-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_restaurantadress_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='adress',
        ),
    ]
