# Generated by Django 4.1.4 on 2023-01-18 19:27

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.FilePathField(path=pathlib.PureWindowsPath('static/img'))),
                ('meal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.meal')),
            ],
        ),
    ]
